# A workspace in a monorepo is an individual sub-project, app, or shared library located inside a single repository
packages:
  - apps/*
  - packages/*  #librerias compartidas

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - sharp
