services:
  catalog_db:
    image: postgres:16-alpine
    container_name: catalog_db
    # para produccion seria un network por servicio aislado
    networks:
      - dugout_network
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${catalog_user}
      POSTGRES_PASSWORD: ${catalog_password}
      POSTGRES_DB: ${catalog_db}
    ports:
        - "5436:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data

  order_db:
    image: postgres:16-alpine
    container_name: order_db
    networks:
      - dugout_network
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${order_user}
      POSTGRES_PASSWORD: ${order_password}
      POSTGRES_DB: ${order_db}
    ports:
      - "5435:5432"
    # aqui Docker guarda los datos de order_db para que no sepierdan al reiniciar
    volumes:
      - order_data:/var/lib/postgresql/data

  auth_db:
    image: postgres:16-alpine
    container_name: auth_db
    networks:
      - dugout_network
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${auth_user}
      POSTGRES_PASSWORD: ${auth_password}
      POSTGRES_DB: ${auth_db}
    ports:
        -   "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  payment_db:
    image: postgres:16-alpine
    container_name: payment_db
    networks:
      - dugout_network
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${payment_user}
      POSTGRES_PASSWORD: ${payment_password}
      POSTGRES_DB: ${payment_db}
    ports:
        - "5433:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
# base de dato de keycloak
  keycloak_db:
    image: postgres:16-alpine
    container_name: keycloak_db
    networks:
      - dugout_network
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${keycloak_user}
      POSTGRES_PASSWORD: ${keycloak_password}
      POSTGRES_DB: ${keycloak_db}
    ports:
      - "5434:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data

# cliente para acceder al ui de keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start-dev
    container_name: keycloak
    networks:
      - dugout_network
    restart: unless-stopped
    depends_on:
      - keycloak_db
    ports:
      - 8080:8080
    environment:
      KC_DB: postgres
      # jdbc java db connectivity, keycloak corre en java, este protocolo le dice a keycloak que se connecte a postgres, keycloak aqui el host, nombre del servicio docker, en la red de docker, los contene se hablar por nombre de servicio no de ip, nombre de la base de dato
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/${keycloak_db}
      KC_DB_USERNAME: ${keycloak_user}
      KC_DB_PASSWORD: ${keycloak_password}
      KEYCLOAK_ADMIN: ${kc_admin}
      KEYCLOAK_ADMIN_PASSWORD: ${kc_admin_password}

      # este servico de keycloak es stateless no guarda anda su estado vive en la db que creamos arriba 


volumes:
  catalog_data:
  order_data:
  auth_data:
  payment_data:
  keycloak_data:

networks:
  dugout_network:
